#!/usr/bin/env npx tsx
// Auto-generate plugin list from packages/plugin-* directories

import { readFileSync, writeFileSync, readdirSync, statSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath } from "url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const rootDir = join(__dirname, "..")
const packagesDir = join(rootDir, "packages")
const outputPath = join(rootDir, "packages/cli/src/generated/plugins.ts")

interface PackageJson {
  name: string
  version: string
  description: string
  gitton?: {
    displayName?: string
    description?: string
  }
}

interface PluginInfo {
  name: string
  shortName: string
  version: string
  description: string
  displayName: string
}

function getPluginPackages(): string[] {
  return readdirSync(packagesDir)
    .filter((dir) => {
      const fullPath = join(packagesDir, dir)
      return (
        dir.startsWith("plugin-") &&
        statSync(fullPath).isDirectory() &&
        statSync(join(fullPath, "package.json")).isFile()
      )
    })
    .sort()
}

function readPackageJson(pluginDir: string): PackageJson {
  const pkgPath = join(packagesDir, pluginDir, "package.json")
  return JSON.parse(readFileSync(pkgPath, "utf-8"))
}

function extractPluginInfo(pkg: PackageJson): PluginInfo {
  const shortName = pkg.name.replace("@gitton-dev/plugin-", "")
  return {
    name: pkg.name,
    shortName,
    version: pkg.version,
    description: pkg.gitton?.description || pkg.description,
    displayName: pkg.gitton?.displayName || shortName,
  }
}

function generatePluginsTs(plugins: PluginInfo[]): string {
  const pluginsJson = JSON.stringify(plugins, null, 2)

  return `// Auto-generated by scripts/generate-plugin-list.ts
// Do not edit manually

export interface PluginInfo {
  name: string
  shortName: string
  version: string
  description: string
  displayName: string
}

export const availablePlugins: PluginInfo[] = ${pluginsJson}
`
}

function main() {
  const pluginDirs = getPluginPackages()
  console.log(`Found ${pluginDirs.length} plugins:`, pluginDirs)

  const plugins = pluginDirs.map((dir) => {
    const pkg = readPackageJson(dir)
    return extractPluginInfo(pkg)
  })

  const content = generatePluginsTs(plugins)
  writeFileSync(outputPath, content)
  console.log(`Generated ${outputPath}`)
}

main()
